# Profiles Config for Clash Verge

current: R1QMFvhUmDSO
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1756019175
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1756019175
- uid: m3CgeDRg54DS
  type: merge
  name: null
  file: m3CgeDRg54DS.yaml
  updated: 1756019786
- uid: sy0eKcY3HAZS
  type: script
  name: null
  file: sy0eKcY3HAZS.js
  updated: 1756019786
- uid: rpai4sJId1bk
  type: rules
  name: null
  file: rpai4sJId1bk.yaml
  updated: 1756019786
- uid: pSv6Mivkj8LR
  type: proxies
  name: null
  file: pSv6Mivkj8LR.yaml
  updated: 1756019786
- uid: gnq77WchVAFz
  type: groups
  name: null
  file: gnq77WchVAFz.yaml
  updated: 1756019786
- uid: R1QMFvhUmDSO
  type: remote
  name: free.yaml
  file: R1QMFvhUmDSO.yaml
  url: https://www.xrayvip.com/free.yaml
  updated: 1756019946
  option:
    merge: m3CgeDRg54DS
    script: sy0eKcY3HAZS
    rules: rpai4sJId1bk
    proxies: pSv6Mivkj8LR
    groups: gnq77WchVAFz
- uid: miH3RBfEKcR7
  type: merge
  name: null
  file: miH3RBfEKcR7.yaml
  updated: 1756019798
- uid: s0mdHtB06q26
  type: script
  name: null
  file: s0mdHtB06q26.js
  updated: 1756019798
- uid: r2BWpD5kNY6E
  type: rules
  name: null
  file: r2BWpD5kNY6E.yaml
  updated: 1756019798
- uid: pEvFG5PfngfJ
  type: proxies
  name: null
  file: pEvFG5PfngfJ.yaml
  updated: 1756019798
- uid: gZfDAIzoUcwN
  type: groups
  name: null
  file: gZfDAIzoUcwN.yaml
  updated: 1756019798
- uid: R2G8kmYN81lx
  type: remote
  name: list.yml
  file: R2G8kmYN81lx.yaml
  url: https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  updated: 1756019943
  option:
    merge: miH3RBfEKcR7
    script: s0mdHtB06q26
    rules: r2BWpD5kNY6E
    proxies: pEvFG5PfngfJ
    groups: gZfDAIzoUcwN
- uid: mux6L3QUQQla
  type: merge
  name: null
  file: mux6L3QUQQla.yaml
  updated: 1756019805
- uid: ss5aGnVbCuMS
  type: script
  name: null
  file: ss5aGnVbCuMS.js
  updated: 1756019805
- uid: rVfnknJGaDzV
  type: rules
  name: null
  file: rVfnknJGaDzV.yaml
  updated: 1756019805
- uid: p9kQEQRikx7S
  type: proxies
  name: null
  file: p9kQEQRikx7S.yaml
  updated: 1756019805
- uid: g35uYLoOQ3sB
  type: groups
  name: null
  file: g35uYLoOQ3sB.yaml
  updated: 1756019805
- uid: RouPwdNZaVsH
  type: remote
  name: list.yml
  file: RouPwdNZaVsH.yaml
  url: https://testingcf.jsdelivr.net/gh/peasoft/NoMoreWalls@master/list.yml
  updated: 1756019941
  option:
    merge: mux6L3QUQQla
    script: ss5aGnVbCuMS
    rules: rVfnknJGaDzV
    proxies: p9kQEQRikx7S
    groups: g35uYLoOQ3sB
- uid: mFDm35kRcxie
  type: merge
  name: null
  file: mFDm35kRcxie.yaml
  updated: 1756019818
- uid: sf3oeGa7kPLY
  type: script
  name: null
  file: sf3oeGa7kPLY.js
  updated: 1756019818
- uid: rywNFJmGj9KJ
  type: rules
  name: null
  file: rywNFJmGj9KJ.yaml
  updated: 1756019818
- uid: ptQqphA4tauA
  type: proxies
  name: null
  file: ptQqphA4tauA.yaml
  updated: 1756019818
- uid: gygKmpiDMCjh
  type: groups
  name: null
  file: gygKmpiDMCjh.yaml
  updated: 1756019818
- uid: RlW4txpSnTc1
  type: remote
  name: list.yml
  file: RlW4txpSnTc1.yaml
  url: https://ghproxy.cfd/https:/raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  updated: 1756019943
  option:
    merge: mFDm35kRcxie
    script: sf3oeGa7kPLY
    rules: rywNFJmGj9KJ
    proxies: ptQqphA4tauA
    groups: gygKmpiDMCjh
