# Profiles Config for Clash Verge

current: RzCWfAFvTeXa
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1756019175
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1756019175
- uid: m3CgeDRg54DS
  type: merge
  name: null
  file: m3CgeDRg54DS.yaml
  updated: 1756019786
- uid: sy0eKcY3HAZS
  type: script
  name: null
  file: sy0eKcY3HAZS.js
  updated: 1756019786
- uid: rpai4sJId1bk
  type: rules
  name: null
  file: rpai4sJId1bk.yaml
  updated: 1756019786
- uid: pSv6Mivkj8LR
  type: proxies
  name: null
  file: pSv6Mivkj8LR.yaml
  updated: 1756019786
- uid: gnq77WchVAFz
  type: groups
  name: null
  file: gnq77WchVAFz.yaml
  updated: 1756019786
- uid: R1QMFvhUmDSO
  type: remote
  name: free.yaml
  file: R1QMFvhUmDSO.yaml
  desc: ''
  url: https://www.xrayvip.com/free.yaml
  selected:
  - name: 🚀 节点选择
    now: 乌克兰【机场推荐：https://a0a.xyz/】8
  updated: 1758454150
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: m3CgeDRg54DS
    script: sy0eKcY3HAZS
    rules: rpai4sJId1bk
    proxies: pSv6Mivkj8LR
    groups: gnq77WchVAFz
- uid: miH3RBfEKcR7
  type: merge
  name: null
  file: miH3RBfEKcR7.yaml
  updated: 1756019798
- uid: s0mdHtB06q26
  type: script
  name: null
  file: s0mdHtB06q26.js
  updated: 1756019798
- uid: r2BWpD5kNY6E
  type: rules
  name: null
  file: r2BWpD5kNY6E.yaml
  updated: 1756019798
- uid: pEvFG5PfngfJ
  type: proxies
  name: null
  file: pEvFG5PfngfJ.yaml
  updated: 1756019798
- uid: gZfDAIzoUcwN
  type: groups
  name: null
  file: gZfDAIzoUcwN.yaml
  updated: 1756019798
- uid: R2G8kmYN81lx
  type: remote
  name: list.yml
  file: R2G8kmYN81lx.yaml
  desc: ''
  url: https://gh-proxy.com/raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  selected:
  - name: ♻ 自动选择
    now: US_speednode_0037
  - name: 🚀 选择代理
    now: 🔰 延迟最低
  updated: 1758454148
  option:
    with_proxy: false
    self_proxy: false
    merge: miH3RBfEKcR7
    script: s0mdHtB06q26
    rules: r2BWpD5kNY6E
    proxies: pEvFG5PfngfJ
    groups: gZfDAIzoUcwN
- uid: mEqIIP7vDEsF
  type: merge
  name: null
  file: mEqIIP7vDEsF.yaml
  updated: 1757385964
- uid: s9p3hAGop1aa
  type: script
  name: null
  file: s9p3hAGop1aa.js
  updated: 1757385964
- uid: r0NR7tnSLk13
  type: rules
  name: null
  file: r0NR7tnSLk13.yaml
  updated: 1757385964
- uid: pJWKr3eLRYV8
  type: proxies
  name: null
  file: pJWKr3eLRYV8.yaml
  updated: 1757385964
- uid: gCx0PsY8JBWW
  type: groups
  name: null
  file: gCx0PsY8JBWW.yaml
  updated: 1757385964
- uid: RJ22OWYRJ1Gs
  type: remote
  name: sub
  file: RJ22OWYRJ1Gs.yaml
  url: https://api.wcc.best/sub?target=clash&url=https:%2F%2Fproxy.v2gh.com%2Fhttps:%2F%2Fraw.githubusercontent.com%2FPawdroid%2FFree-servers%2Fmain%2Fsub&insert=false&config=https:%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&emoji=true&list=false&tfo=false&scv=true&fdn=false&expand=true&sort=false&new_name=true
  selected:
  - name: 🚀 节点选择
    now: 🇺🇸 美国 V2CROSS.COM 2
  updated: 1758454148
  option:
    update_interval: 1440
    merge: mEqIIP7vDEsF
    script: s9p3hAGop1aa
    rules: r0NR7tnSLk13
    proxies: pJWKr3eLRYV8
    groups: gCx0PsY8JBWW
- uid: m17flY2wkJGN
  type: merge
  name: null
  file: m17flY2wkJGN.yaml
  updated: 1757387542
- uid: s1KfOCTWvLUn
  type: script
  name: null
  file: s1KfOCTWvLUn.js
  updated: 1757387542
- uid: rsv811pc6MtC
  type: rules
  name: null
  file: rsv811pc6MtC.yaml
  updated: 1757387542
- uid: pIenP4XtQ3kW
  type: proxies
  name: null
  file: pIenP4XtQ3kW.yaml
  updated: 1757387542
- uid: gK2p9kXEiObQ
  type: groups
  name: null
  file: gK2p9kXEiObQ.yaml
  updated: 1757387542
- uid: R8gZjmES6YI5
  type: remote
  name: mihomo.yaml
  file: R8gZjmES6YI5.yaml
  desc: ''
  url: https://gh-proxy.com/raw.githubusercontent.com/shaoyouvip/free/main/mihomo.yaml
  selected:
  - name: 🚀 节点选择
    now: ♻️ 自动选择
  updated: 1758454148
  option:
    with_proxy: false
    self_proxy: false
    merge: m17flY2wkJGN
    script: s1KfOCTWvLUn
    rules: rsv811pc6MtC
    proxies: pIenP4XtQ3kW
    groups: gK2p9kXEiObQ
- uid: mxS2b0kO6yAb
  type: merge
  name: null
  file: mxS2b0kO6yAb.yaml
  updated: 1757387651
- uid: s0fpUyDWeOdo
  type: script
  name: null
  file: s0fpUyDWeOdo.js
  updated: 1757387651
- uid: rs8Xe4v35XPl
  type: rules
  name: null
  file: rs8Xe4v35XPl.yaml
  updated: 1757387651
- uid: p8ax70A8oeI8
  type: proxies
  name: null
  file: p8ax70A8oeI8.yaml
  updated: 1757387651
- uid: gyRqJBTRbuLB
  type: groups
  name: null
  file: gyRqJBTRbuLB.yaml
  updated: 1757387651
- uid: R676f6Ss0Sjy
  type: remote
  name: proxies.yaml
  file: R676f6Ss0Sjy.yaml
  desc: ''
  url: https://gh-proxy.com/raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml
  selected:
  - name: 🔰 节点选择
    now: at|9d9a|puddincat07@Telegram
  updated: 1758454148
  option:
    with_proxy: false
    self_proxy: false
    merge: mxS2b0kO6yAb
    script: s0fpUyDWeOdo
    rules: rs8Xe4v35XPl
    proxies: p8ax70A8oeI8
    groups: gyRqJBTRbuLB
- uid: myAfmFwNURCc
  type: merge
  name: null
  file: myAfmFwNURCc.yaml
  updated: 1758015327
- uid: sXfLsW37QRjg
  type: script
  name: null
  file: sXfLsW37QRjg.js
  updated: 1758015327
- uid: rknzgllLIBI5
  type: rules
  name: null
  file: rknzgllLIBI5.yaml
  updated: 1758015327
- uid: pKE9L0oCTEsP
  type: proxies
  name: null
  file: pKE9L0oCTEsP.yaml
  updated: 1758015327
- uid: gJYIY1zOyjZs
  type: groups
  name: null
  file: gJYIY1zOyjZs.yaml
  updated: 1758015327
- uid: RzCWfAFvTeXa
  type: remote
  name: Jsnzkpg
  file: RzCWfAFvTeXa.yaml
  url: https://gh-proxy.com/https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg
  updated: 1758454149
  option:
    merge: myAfmFwNURCc
    script: sXfLsW37QRjg
    rules: rknzgllLIBI5
    proxies: pKE9L0oCTEsP
    groups: gJYIY1zOyjZs
