# Profiles Config for Clash Verge

current: R8gZjmES6YI5
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1756019175
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1756019175
- uid: m17flY2wkJGN
  type: merge
  name: null
  file: m17flY2wkJGN.yaml
  updated: 1757387542
- uid: s1KfOCTWvLUn
  type: script
  name: null
  file: s1KfOCTWvLUn.js
  updated: 1757387542
- uid: rsv811pc6MtC
  type: rules
  name: null
  file: rsv811pc6MtC.yaml
  updated: 1757387542
- uid: pIenP4XtQ3kW
  type: proxies
  name: null
  file: pIenP4XtQ3kW.yaml
  updated: 1757387542
- uid: gK2p9kXEiObQ
  type: groups
  name: null
  file: gK2p9kXEiObQ.yaml
  updated: 1757387542
- uid: R8gZjmES6YI5
  type: remote
  name: mihomo.yaml
  file: R8gZjmES6YI5.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/shaoyouvip/free/main/mihomo.yaml
  selected:
  - name: 🚀 节点选择
    now: 🚀 手动切换
  - name: 🚀 手动切换
    now: 🇮🇹IT_2|1.4MB/s
  - name: ♻️ 自动选择
    now: sg|ab66|puddincat07@Telegram
  updated: 1775176599
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: m17flY2wkJGN
    script: s1KfOCTWvLUn
    rules: rsv811pc6MtC
    proxies: pIenP4XtQ3kW
    groups: gK2p9kXEiObQ
- uid: mxS2b0kO6yAb
  type: merge
  name: null
  file: mxS2b0kO6yAb.yaml
  updated: 1757387651
- uid: s0fpUyDWeOdo
  type: script
  name: null
  file: s0fpUyDWeOdo.js
  updated: 1757387651
- uid: rs8Xe4v35XPl
  type: rules
  name: null
  file: rs8Xe4v35XPl.yaml
  updated: 1757387651
- uid: p8ax70A8oeI8
  type: proxies
  name: null
  file: p8ax70A8oeI8.yaml
  updated: 1757387651
- uid: gyRqJBTRbuLB
  type: groups
  name: null
  file: gyRqJBTRbuLB.yaml
  updated: 1757387651
- uid: R676f6Ss0Sjy
  type: remote
  name: proxies.yaml
  file: R676f6Ss0Sjy.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml
  selected:
  - name: 🔰 节点选择
    now: nl|d7c4|puddincat07@Telegram
  - name: ♻️ 自动选择
    now: gb|1593|puddincat07@Telegram
  - name: Proxy
    now: 🇺🇸 美国节点
  updated: 1775182999
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mxS2b0kO6yAb
    script: s0fpUyDWeOdo
    rules: rs8Xe4v35XPl
    proxies: p8ax70A8oeI8
    groups: gyRqJBTRbuLB
- uid: myAfmFwNURCc
  type: merge
  name: null
  file: myAfmFwNURCc.yaml
  updated: 1758015327
- uid: sXfLsW37QRjg
  type: script
  name: null
  file: sXfLsW37QRjg.js
  updated: 1758015327
- uid: rknzgllLIBI5
  type: rules
  name: null
  file: rknzgllLIBI5.yaml
  updated: 1758015327
- uid: pKE9L0oCTEsP
  type: proxies
  name: null
  file: pKE9L0oCTEsP.yaml
  updated: 1758015327
- uid: gJYIY1zOyjZs
  type: groups
  name: null
  file: gJYIY1zOyjZs.yaml
  updated: 1758015327
- uid: RzCWfAFvTeXa
  type: remote
  name: Jsnzkpg
  file: RzCWfAFvTeXa.yaml
  desc: ''
  url: https://gh-proxy.org/https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg
  selected:
  - name: 🚀 手动切换
    now: 🇫🇷FR_2|1.2MB/s
  - name: 🚀 节点选择
    now: 🚀 手动切换
  - name: Haita Cloud
    now: 下单地址https://kelayun.notepin.co
  - name: 🔰 节点选择
    now: kr|71a5|puddincat07@Telegram
  - name: 自动选择
    now: 官网地址https://kelayun.notepin.co
  - name: Proxy
    now: 🇰🇷 韩国节点
  updated: 1775182997
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: myAfmFwNURCc
    script: sXfLsW37QRjg
    rules: rknzgllLIBI5
    proxies: pKE9L0oCTEsP
    groups: gJYIY1zOyjZs
- uid: m3kStCZES4OO
  type: merge
  name: null
  file: m3kStCZES4OO.yaml
  updated: 1763605415
- uid: sxIcjTLuDoVI
  type: script
  name: null
  file: sxIcjTLuDoVI.js
  updated: 1763605415
- uid: r7LimxXOI78b
  type: rules
  name: null
  file: r7LimxXOI78b.yaml
  updated: 1763605415
- uid: pooOIH02hHEr
  type: proxies
  name: null
  file: pooOIH02hHEr.yaml
  updated: 1763605415
- uid: gam20kDdzk1L
  type: groups
  name: null
  file: gam20kDdzk1L.yaml
  updated: 1763605415
- uid: Riq04bVZSqC1
  type: remote
  name: 11clash
  file: Riq04bVZSqC1.yaml
  desc: ''
  url: https://gh-proxy.org/https://raw.githubusercontent.com/ggborr/FREEE-VPN/refs/heads/main/2clash
  selected:
  - name: 🚀 节点选择
    now: 关注https://github.com/ggborr/FREEE-VPN
  updated: 1775176600
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: m3kStCZES4OO
    script: sxIcjTLuDoVI
    rules: r7LimxXOI78b
    proxies: pooOIH02hHEr
    groups: gam20kDdzk1L
- uid: moAUGs2e9TRa
  type: merge
  name: null
  file: moAUGs2e9TRa.yaml
  updated: 1765712487
- uid: sKJEZZNHrno1
  type: script
  name: null
  file: sKJEZZNHrno1.js
  updated: 1765712487
- uid: rRmZafm16Wwk
  type: rules
  name: null
  file: rRmZafm16Wwk.yaml
  updated: 1765712487
- uid: pCh4xbwWseOr
  type: proxies
  name: null
  file: pCh4xbwWseOr.yaml
  updated: 1765712487
- uid: gjkHkO3KqD2G
  type: groups
  name: null
  file: gjkHkO3KqD2G.yaml
  updated: 1765712487
- uid: RX0QsdMN538J
  type: remote
  name: clash
  file: RX0QsdMN538J.yaml
  desc: ''
  url: https://gh-proxy.org//https://raw.githubusercontent.com/ts-sf/fly/main/clash
  selected:
  - name: 🚀 节点选择
    now: 🇺🇸US美国18 581.3KB/s
  - name: 🚀 手动切换
    now: 🇸🇬SG_3|1.7MB/s
  updated: 1775176600
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: moAUGs2e9TRa
    script: sKJEZZNHrno1
    rules: rRmZafm16Wwk
    proxies: pCh4xbwWseOr
    groups: gjkHkO3KqD2G
- uid: mY3wtAG1LwFS
  type: merge
  name: null
  file: mY3wtAG1LwFS.yaml
  updated: 1773399680
- uid: sFx2zTnclq0F
  type: script
  name: null
  file: sFx2zTnclq0F.js
  updated: 1773399680
- uid: rvzhAziCnBAJ
  type: rules
  name: null
  file: rvzhAziCnBAJ.yaml
  updated: 1773399680
- uid: pcGFv8PJJyNg
  type: proxies
  name: null
  file: pcGFv8PJJyNg.yaml
  updated: 1773399680
- uid: g0WyTIUds2Ki
  type: groups
  name: null
  file: g0WyTIUds2Ki.yaml
  updated: 1773399680
- uid: RrsdrdP7Opk4
  type: remote
  name: yudou66.yaml
  file: RrsdrdP7Opk4.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.yaml
  selected:
  - name: 🚀 节点选择
    now: 韩国(yudou789.top 玉豆免费节点)_1
  updated: 1775176599
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: mY3wtAG1LwFS
    script: sFx2zTnclq0F
    rules: rvzhAziCnBAJ
    proxies: pcGFv8PJJyNg
    groups: g0WyTIUds2Ki
- uid: mfXNjaNyx19s
  type: merge
  name: null
  file: mfXNjaNyx19s.yaml
  updated: 1774265164
- uid: s6aakWpqIgXG
  type: script
  name: null
  file: s6aakWpqIgXG.js
  updated: 1774265164
- uid: rIQ1BDlmzNUi
  type: rules
  name: null
  file: rIQ1BDlmzNUi.yaml
  updated: 1774265164
- uid: p6EBiANjjnVa
  type: proxies
  name: null
  file: p6EBiANjjnVa.yaml
  updated: 1774265164
- uid: ge2fpr6vZZUj
  type: groups
  name: null
  file: ge2fpr6vZZUj.yaml
  updated: 1774265164
- uid: RClhMvILjc3E
  type: remote
  name: mihomo.yaml
  file: RClhMvILjc3E.yaml
  desc: ''
  url: https://gh-proxy.org/https://raw.githubusercontent.com/ovmvo/FreeSub/refs/heads/main/sub/permanent/mihomo.yaml
  selected:
  - name: Proxy
    now: 🎡负载均衡
  updated: 1775176599
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: mfXNjaNyx19s
    script: s6aakWpqIgXG
    rules: rIQ1BDlmzNUi
    proxies: p6EBiANjjnVa
    groups: ge2fpr6vZZUj
